### PR TITLE
[Refactor] Rename "DAG" to "CircuitSeq"

### PR DESCRIPTION
**Pull request by xumingkuan**
Related issue = #60 

This PR does the refactoring proposed in the issue.

It does not rename every local variable from `dag` to `seq`, from `node` to `wire`, or from `edge` to `gate` or `circuit_gate`, simply because there are too many places using them. Contributions are welcome if anyone can help rename them!

### CODE REVIEW

**Comment by xumingkuan** [comment]
@zikun-li Could you please review the Cython part? I'm not sure about my change there.

**Comment by zikun-li** [comment]
Sure! I'll take a look

**Comment by zikun-li** [comment]
I've checked the cython files and I think they looks good.

**Comment by xumingkuan** [comment]
Merging this PR now and please also do the refactoring in other branches at your convenience after merging/rebasing/cherry-picking this PR. Sorry for the burden but `DAG` is used everywhere... an example is https://github.com/quantum-compiler/quartz/commit/39e28443c50c14556b19d8829e789497b4ed7039.

**Pull request merged**
