### PR TITLE
[Simulator] Separate CUDA/Legion-related parts out of Quartz

### PR DESCRIPTION
**Pull request by xumingkuan**
This PR aims to remove all CUDA/Legion-related parts from Quartz, so we don't need to have a dependency on CUDA anymore.

In the part unrelated to the simulator, this PR adds more circuits and also merges #106 and #109 to the master branch.

### CODE REVIEW

**Comment by xumingkuan** [comment]
I don't think I touched anything in the `experiment/` folder but the pre-commit check is failing on it... @Co1lin Do you know why this is possible?

**Comment by Co1lin** [comment]
It's weird... The versions of `pre-commit` and hooks are the same. The files under `experiment` like `experiment/ppo-new/greedy_search.py` are also the same. But if you run `pre-commit run --all-files` on the master branch, it passes while running it on [simulator-to-be-merged](https://github.com/quantum-compiler/quartz/tree/simulator-to-be-merged) fails (on my local machine).

**Comment by xumingkuan** [comment]
Ok I'll leave the folder `config/` there to make `isort` happy for now.
@Co1lin We may need to change `from config.config import *` to the full path in order to be recognized by `isort` as first-party modules. For example, we may want to change this line in `experiment/ppo-ablation/ppo.py` to `from experiment.ppo-ablation.config.config import *` but I'm not sure if this works or not. Also, it seems that the changeset will be large. I don't know if there is an easier way to make `isort` recognize that `config` is a first-party module.
@caoshiyi Could you please review this PR when you're available? Thanks!

**Review by caoshiyi — COMMENTED** [review]
Looks good!

**Pull request merged**
