### PR TITLE
add arb as a library

### PR DESCRIPTION
**Pull request by umutacar**
This PR adds arb as a submodule under 'lib/arb' 
Maintaining submodules can be a bit tricky
We can talk about it in person

## TODO
We will need to update the code to use this local version rather that the dynamically linked version

### CODE REVIEW

**Review by xumingkuan — COMMENTED** [review]
We may need to figure out how to deal with Arb's dependencies. For example, on Windows when there is no GMP, if we include Arb as a submodule, it seems that there's no way to build Quartz without Arb, and we will get build errors when we build Quartz with Arb because Arb doesn't compile without GMP...

**Comment by jiazhihao** [comment]
Do we still need to add Arb to Quartz?

**Comment by xumingkuan** [comment]
I think it's probably not necessary because the floating point error is not large.

**Comment by jiazhihao** [comment]
Today happens to be the one-year anniversary of this PR. Should we close it?

**Comment by xumingkuan** [comment]
Closing as it seems that Arb is not necessary.

**Pull request closed without merging**
